### ISSUE TITLE
Option to disable the keydown event?

### ISSUE THREAD

**Issue by conhuynh** [Mobius1/Pageable#15]
Hi,

Thanks for the great plugin!

Is it possible to add in an option to disable the keydown event? 

This appears to be hijacking other keydown events I have on the page - like with inputs.

Something like
```
events: {
    keydown: false,
}
```

**Comment by Mobius1** [comment]
I'll add this for the next release or I'm happy to accept a pull request.

**Comment by Mobius1** [comment]
This has now been implemented in [`0.6.3`](https://github.com/Mobius1/Pageable/releases/tag/0.6.3).

**Comment by conhuynh** [comment]
Awesome, works great.

Thank you so much for the prompt action.
