### ISSUE TITLE
playground - anchors on the right are without function

### ISSUE THREAD

**Issue by gseilheimer** [Mobius1/Pageable#2]
first: that‘s a great demo of this library.

second: the anchor links on the right are out of functionality if you click on it.

**Comment by Mobius1** [comment]
Is it the pips or the actual page title anchors?

**Comment by gseilheimer** [comment]
![bildschirmfoto 2018-11-27 um 20 36 25](https://user-images.githubusercontent.com/458596/49106939-c20c7000-f284-11e8-9310-d633c8f88c49.png)
![bildschirmfoto 2018-11-27 um 20 38 45](https://user-images.githubusercontent.com/458596/49106941-c20c7000-f284-11e8-9b2f-3ccb2101eb40.png)
