### ISSUE TITLE
[bug] events inside box doesn`t works

### ISSUE THREAD

**Issue by nikitamarcius** [Mobius1/Pageable#22]
Events inside box doesn`t works on mobile chrome browser. 
Chrome 77.0.3865.116

```
	const options = {
		pips: true,
		infinite: true,
		easing: function(currentTime, startPos, endPos, interval) {
			// the easing function used for the scroll animation
			return -endPos * (currentTime /= interval) * (currentTime - 2) + startPos;
		},
	}
```

![Безымянный](https://user-images.githubusercontent.com/10992863/67138465-36a91e00-f24c-11e9-93eb-6296ac76acde.png)

**More:**

Plugin works well only in the web version on a real mobile device works like shit. Why does pugin try to render a block every time? he doesn’t succeed, the layout floats loaded for a long time. Why can't you make a dumb scroll from block to block only? 
This is not ready for production, please correct the errors or do not mislead people so that there is no waste of time

**Comment by Mobius1** [comment]
> This is not ready for production, please correct the errors or do not mislead people so that there is no waste of time

What the hell are you flapping about? Misleading? The lib is in `0.x.x` form and hence anyone with half a brain cell would know it's not production-ready.

**Comment by nikitamarcius** [comment]
@Mobius1 i don't care about the package version. 
Public plugin? - Yes. Plugin`s task - onepage scrolling. Can perform main task? - 50 / 50.
You either do well or don’t do at all.

**Comment by nikitamarcius** [comment]
@Mobius1 sorry for my harshness. I can help test plugin and give feedback to finalize. 
If collaboration is interesting, write in Telegram: https://t.me/nikitamarcius or Discord: Nikita Marcius#2274

**Comment by nikitamarcius** [comment]
https://github.com/Mobius1/Pageable/issues/14
