### ISSUE TITLE
Drag and swipe distance before trigger event

### ISSUE THREAD

**Issue by EikiProg** [Mobius1/Pageable#4]
Hello,
Is it possible to put a custom distance before the drag or swipe event is fired ?
Now it's like 1px down or up trigger the related event but I added a slider inside with swipe/drag and if i don't do a perfect line left or right then it change page and don't slide.

**Comment by Mobius1** [comment]
That's definitely something that can be implemented.

**Comment by Mobius1** [comment]
Try the new `swipeThreshold` option when using `v0.2.3` or above. Set an integer for the number of pixels before the page change event is fired.
