### ISSUE TITLE
Drag and hold before move

### ISSUE THREAD

**Issue by waelabdrabbo** [Mobius1/Pageable#5]
Hi,

it is possible to make the dragging movements show some pixels of the next sections before jump to it like [http://kenwheeler.github.io/slick/](http://kenwheeler.github.io/slick/) ?

Thanks

**Comment by Mobius1** [comment]
This feature will be added in the next release 👍

**Comment by Mobius1** [comment]
Try the `freeScroll` option when using `v0.3.6` and above.

**Comment by waelabdrabbo** [comment]
it's work like a charm, thanks.
